# Generated by Django 4.1.2 on 2022-10-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead', models.CharField(max_length=150)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('services', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('channels', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('saleRepresentative', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('signed_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potentialleads.question')),
            ],
        ),
    ]
